import Providers from "./utlis/provider";
import React from "react";
import "./globals.css";

export const metadata = {
  title: "Bansdih Vidhan Sabha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
